
package InterfazGrafica;

import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Cliente extends javax.swing.JFrame 
{
    Socket cliente;
    DataOutputStream salida;
    DataInputStream entrada;

    public Cliente() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ParqueAcuatico = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ControlUbicacion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Ubicacion = new javax.swing.JLabel();
        Actividades = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textUbicacion = new javax.swing.JTextField();
        textActividades = new javax.swing.JTextField();
        botonUbicacion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ControlToboganes = new javax.swing.JLabel();
        ToboganA = new javax.swing.JLabel();
        ToboganB = new javax.swing.JLabel();
        ToboganC = new javax.swing.JLabel();
        textToboganA = new javax.swing.JTextField();
        textToboganB = new javax.swing.JTextField();
        textToboganC = new javax.swing.JTextField();
        botonToboganes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ControMenores = new javax.swing.JLabel();
        NumMenores = new javax.swing.JLabel();
        textNumMenores = new javax.swing.JTextField();
        botonMenores = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ControlAforo = new javax.swing.JLabel();
        Vestuario = new javax.swing.JLabel();
        PiscinaGrande = new javax.swing.JLabel();
        PiscinaOlas = new javax.swing.JLabel();
        PiscinaNiños = new javax.swing.JLabel();
        Tumbonas = new javax.swing.JLabel();
        Toboganes = new javax.swing.JLabel();
        textVestuario = new javax.swing.JTextField();
        textPiscinaGrande = new javax.swing.JTextField();
        textPiscinaOlas = new javax.swing.JTextField();
        textPiscinaNiños = new javax.swing.JTextField();
        textTumbonas = new javax.swing.JTextField();
        textToboganes = new javax.swing.JTextField();
        botonAforo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                                                                                                       ***CONTROL PARQUE ACUÁTICO - PEC3L***");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        ParqueAcuatico.setBackground(new java.awt.Color(0, 102, 204));
        ParqueAcuatico.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 16)); // NOI18N
        ParqueAcuatico.setForeground(new java.awt.Color(255, 255, 255));
        ParqueAcuatico.setText("                   PARQUE  ACUÁTICO");
        ParqueAcuatico.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        ControlUbicacion.setBackground(new java.awt.Color(0, 153, 153));
        ControlUbicacion.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        ControlUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        ControlUbicacion.setText("      CONTROL DE UBICACIÓN");
        ControlUbicacion.setOpaque(true);

        Usuario.setBackground(new java.awt.Color(0, 153, 204));
        Usuario.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("             USUARIO:");
        Usuario.setOpaque(true);

        Ubicacion.setBackground(new java.awt.Color(0, 153, 204));
        Ubicacion.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        Ubicacion.setText("           UBICACIÓN:");
        Ubicacion.setOpaque(true);

        Actividades.setBackground(new java.awt.Color(0, 153, 204));
        Actividades.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Actividades.setForeground(new java.awt.Color(255, 255, 255));
        Actividades.setText("         ACTIVIDADES:");
        Actividades.setOpaque(true);

        textUbicacion.setEditable(false);

        textActividades.setEditable(false);

        botonUbicacion.setBackground(new java.awt.Color(0, 204, 204));
        botonUbicacion.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        botonUbicacion.setText("BUSCAR");
        botonUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUbicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textUbicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(textUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textActividades)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(botonUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(ControlUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(botonUbicacion)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        ControlToboganes.setBackground(new java.awt.Color(0, 153, 153));
        ControlToboganes.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        ControlToboganes.setForeground(new java.awt.Color(255, 255, 255));
        ControlToboganes.setText("      CONTROL DE TOBOGANES");
        ControlToboganes.setOpaque(true);

        ToboganA.setBackground(new java.awt.Color(0, 153, 204));
        ToboganA.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        ToboganA.setForeground(new java.awt.Color(255, 255, 255));
        ToboganA.setText("           TOBOGÁN A:");
        ToboganA.setOpaque(true);

        ToboganB.setBackground(new java.awt.Color(0, 153, 204));
        ToboganB.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        ToboganB.setForeground(new java.awt.Color(255, 255, 255));
        ToboganB.setText("           TOBOGÁN B:");
        ToboganB.setOpaque(true);

        ToboganC.setBackground(new java.awt.Color(0, 153, 204));
        ToboganC.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        ToboganC.setForeground(new java.awt.Color(255, 255, 255));
        ToboganC.setText("           TOBOGÁN C:");
        ToboganC.setOpaque(true);

        textToboganA.setEditable(false);

        textToboganB.setEditable(false);
        textToboganB.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        textToboganC.setEditable(false);

        botonToboganes.setBackground(new java.awt.Color(0, 204, 204));
        botonToboganes.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonToboganes.setForeground(new java.awt.Color(255, 255, 255));
        botonToboganes.setText("BUSCAR");
        botonToboganes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonToboganesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(ControlToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonToboganes)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(ControlToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToboganC))
                .addGap(41, 41, 41)
                .addComponent(botonToboganes)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        ControMenores.setBackground(new java.awt.Color(0, 153, 153));
        ControMenores.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        ControMenores.setForeground(new java.awt.Color(255, 255, 255));
        ControMenores.setText("     CONTROL DE MENORES");
        ControMenores.setOpaque(true);

        NumMenores.setBackground(new java.awt.Color(0, 153, 204));
        NumMenores.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        NumMenores.setForeground(new java.awt.Color(255, 255, 255));
        NumMenores.setText("    NUM MENORES:");
        NumMenores.setOpaque(true);

        textNumMenores.setEditable(false);

        botonMenores.setBackground(new java.awt.Color(0, 204, 204));
        botonMenores.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonMenores.setForeground(new java.awt.Color(255, 255, 255));
        botonMenores.setText("BUSCAR");
        botonMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(botonMenores))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(ControMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(NumMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textNumMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNumMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMenores)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        ControlAforo.setBackground(new java.awt.Color(0, 153, 153));
        ControlAforo.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        ControlAforo.setForeground(new java.awt.Color(255, 255, 255));
        ControlAforo.setText("      CONTROL DE AFORO");
        ControlAforo.setOpaque(true);

        Vestuario.setBackground(new java.awt.Color(0, 153, 204));
        Vestuario.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Vestuario.setForeground(new java.awt.Color(255, 255, 255));
        Vestuario.setText("        VESTUARIO:");
        Vestuario.setOpaque(true);

        PiscinaGrande.setBackground(new java.awt.Color(0, 153, 204));
        PiscinaGrande.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        PiscinaGrande.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaGrande.setText("   PISCINA GRANDE:");
        PiscinaGrande.setOpaque(true);

        PiscinaOlas.setBackground(new java.awt.Color(0, 153, 204));
        PiscinaOlas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        PiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaOlas.setText("      PISCINA OLAS:");
        PiscinaOlas.setOpaque(true);

        PiscinaNiños.setBackground(new java.awt.Color(0, 153, 204));
        PiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        PiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaNiños.setText("     PISCINA NIÑOS:");
        PiscinaNiños.setOpaque(true);

        Tumbonas.setBackground(new java.awt.Color(0, 153, 204));
        Tumbonas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Tumbonas.setForeground(new java.awt.Color(255, 255, 255));
        Tumbonas.setText("        TUMBONAS:");
        Tumbonas.setOpaque(true);

        Toboganes.setBackground(new java.awt.Color(0, 153, 204));
        Toboganes.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        Toboganes.setForeground(new java.awt.Color(255, 255, 255));
        Toboganes.setText("      TOBOGANES:");
        Toboganes.setOpaque(true);

        textVestuario.setEditable(false);

        textPiscinaGrande.setEditable(false);

        textPiscinaOlas.setEditable(false);

        textPiscinaNiños.setEditable(false);

        textTumbonas.setEditable(false);

        textToboganes.setEditable(false);

        botonAforo.setBackground(new java.awt.Color(0, 204, 204));
        botonAforo.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonAforo.setForeground(new java.awt.Color(255, 255, 255));
        botonAforo.setText("BUSCAR");
        botonAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAforoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(PiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Vestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(PiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(PiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Tumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Toboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(ControlAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(botonAforo)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Toboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(botonAforo)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(648, 648, 648))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUbicacionActionPerformed
        //Buscar la ubicación del usuario del ID introducido
        try 
        {
            String operacion = "UBICACION";
            String identificador = textUsuario.getText();
            String ubicacion;
            String numActividades;
            cliente = new Socket(InetAddress.getLocalHost(), 5000);
            entrada = new DataInputStream(cliente.getInputStream());  
            salida = new DataOutputStream(cliente.getOutputStream());
            salida.writeUTF(operacion);
            salida.writeUTF(identificador);
            ubicacion = entrada.readUTF();
            numActividades = entrada.readUTF();
            salida.close();
            entrada.close();
            cliente.close();
            textUbicacion.setText(ubicacion);
            textActividades.setText(numActividades);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonUbicacionActionPerformed

    private void botonMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenoresActionPerformed
        //Mostrar por pantalla el número de menores que hay actualmente en el parque
        try 
        {
            String operacion = "NUMMENORES";
            String numMenores;
            cliente = new Socket(InetAddress.getLocalHost(), 5000);
            entrada = new DataInputStream(cliente.getInputStream());  
            salida = new DataOutputStream(cliente.getOutputStream());
            salida.writeUTF(operacion);
            numMenores = entrada.readUTF();
            salida.close();
            entrada.close();
            cliente.close();
            textNumMenores.setText(numMenores);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonMenoresActionPerformed

    private void botonToboganesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonToboganesActionPerformed
        //Mostrar los usuarios que están usando en ese momento el tobogán
        try 
        {
            String operacion = "TOBOGANES";
            String toboganA;
            String toboganB;
            String toboganC;
            cliente = new Socket(InetAddress.getLocalHost(), 5000);
            entrada = new DataInputStream(cliente.getInputStream());  
            salida = new DataOutputStream(cliente.getOutputStream());
            salida.writeUTF(operacion);
            toboganA = entrada.readUTF();
            toboganB = entrada.readUTF();
            toboganC = entrada.readUTF();
            salida.close();
            entrada.close();
            cliente.close();
            textToboganA.setText(toboganA);
            textToboganB.setText(toboganB);
            textToboganC.setText(toboganC);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonToboganesActionPerformed

    private void botonAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAforoActionPerformed
        //Muestra el aforo actual de cada actividad
        try 
        {
            String operacion = "AFORO";
            String vestuarios;
            String piscinaOlas;
            String piscinaNinios;
            String tumbonas;
            String toboganes;
            String psicinaGrande;
            cliente = new Socket(InetAddress.getLocalHost(), 5000);
            entrada = new DataInputStream(cliente.getInputStream());  
            salida = new DataOutputStream(cliente.getOutputStream());
            salida.writeUTF(operacion);
            vestuarios = entrada.readUTF();
            piscinaOlas = entrada.readUTF();
            piscinaNinios = entrada.readUTF();
            tumbonas = entrada.readUTF();
            toboganes = entrada.readUTF();
            psicinaGrande = entrada.readUTF();
            salida.close();
            entrada.close();
            cliente.close();
            textVestuario.setText(vestuarios);
            textPiscinaOlas.setText(piscinaOlas);
            textPiscinaNiños.setText(piscinaNinios);
            textTumbonas.setText(tumbonas);
            textToboganes.setText(toboganes);
            textPiscinaGrande.setText(psicinaGrande);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAforoActionPerformed

    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actividades;
    private javax.swing.JLabel ControMenores;
    private javax.swing.JLabel ControlAforo;
    private javax.swing.JLabel ControlToboganes;
    private javax.swing.JLabel ControlUbicacion;
    private javax.swing.JLabel NumMenores;
    private javax.swing.JLabel ParqueAcuatico;
    private javax.swing.JLabel PiscinaGrande;
    private javax.swing.JLabel PiscinaNiños;
    private javax.swing.JLabel PiscinaOlas;
    private javax.swing.JLabel ToboganA;
    private javax.swing.JLabel ToboganB;
    private javax.swing.JLabel ToboganC;
    private javax.swing.JLabel Toboganes;
    private javax.swing.JLabel Tumbonas;
    private javax.swing.JLabel Ubicacion;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Vestuario;
    private javax.swing.JButton botonAforo;
    private javax.swing.JButton botonMenores;
    private javax.swing.JButton botonToboganes;
    private javax.swing.JButton botonUbicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField textActividades;
    private javax.swing.JTextField textNumMenores;
    private javax.swing.JTextField textPiscinaGrande;
    private javax.swing.JTextField textPiscinaNiños;
    private javax.swing.JTextField textPiscinaOlas;
    private javax.swing.JTextField textToboganA;
    private javax.swing.JTextField textToboganB;
    private javax.swing.JTextField textToboganC;
    private javax.swing.JTextField textToboganes;
    private javax.swing.JTextField textTumbonas;
    private javax.swing.JTextField textUbicacion;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JTextField textVestuario;
    // End of variables declaration//GEN-END:variables
}
