
package InterfazGrafica;

import ParqueAcuatico.Monitor;
import ParqueAcuatico.ParqueAcuatico;
import java.util.logging.Level;
import java.util.logging.Logger;
import Usuarios.GeneradorUsuarios;

public class GraficaParqueAcuatico extends javax.swing.JFrame 
{
    private final Paso paso = new Paso();
    private boolean botonPulsado = false;
    
    public GraficaParqueAcuatico() throws InterruptedException 
    {
        initComponents();
        //Creamos el parque con todos los JTextField y dentro de el se crearan los Vestuarios y Atracciones
        ParqueAcuatico pa = new ParqueAcuatico(listaColaEntradaParqueAcuatico, listaColaEntradaVestuario, listaUsuariosDentroVestuario, listaColaEntradaPiscinaGrande, listaUsuariosDentroPiscinaGrande, listaColaEntradaPiscinaNiños, listaNiñosDentroPiscinaNiños, listaAdultosDentroPiscinaNiños, listaColaEntradaPiscinaOlas, listaColaEntradaToboganes, usuarioToboganA, usuarioToboganB, usuarioToboganC, listaColaEntradaTumbonas, listaUsuariosDentroTumbonas, usuarioAtendidoVestuario, usuarioAtendidoPiscinaGrande, usuarioAtendidoPiscinaNiños, usuarioAtendidoPiscinaOlas, usuarioAtendidoTumbonas, listaUsuariosDentroPiscinaOlas, usuarioAtendidoToboganA, usuarioAtendidoToboganB, usuarioAtendidoToboganC);
        
        //Creamos el hilo generador de hilos
        GeneradorUsuarios g = new GeneradorUsuarios(pa, paso);
        g.start();
        
        //Creamos los hilos de los monitores, no podemos usar un bucle for para mayor comodidad porque a cada uno le tenemos que pasar distintos JTextField
        Monitor m1 = new Monitor (1, pa, paso, usuarioAtendidoVestuario);
        m1.start();
        Monitor m2 = new Monitor (2, pa, paso, usuarioAtendidoPiscinaNiños);
        m2.start();
        Monitor m3 = new Monitor (3, pa, paso, usuarioAtendidoPiscinaGrande);
        m3.start();
        Monitor m4 = new Monitor (4, pa, paso, usuarioAtendidoPiscinaOlas);
        m4.start();
        Monitor m5 = new Monitor (5, pa, paso, usuarioAtendidoTumbonas);
        m5.start();
        Monitor m6 = new Monitor (6, pa, paso, usuarioAtendidoToboganA);
        m6.start();
        Monitor m7 = new Monitor (7, pa, paso, usuarioAtendidoToboganB);
        m7.start();
        Monitor m8 = new Monitor (8, pa, paso, usuarioAtendidoToboganC);   
        m8.start();
        
        //Creamos el hilo del servidor
        Servidor s = new Servidor (pa);
        s.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ParqueAcuatico = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        listaColaEntradaParqueAcuatico = new javax.swing.JTextField();
        colaEntradaParqueAcuatico = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Vestuario = new javax.swing.JLabel();
        listaColaEntradaVestuario = new javax.swing.JTextField();
        usuarioAtendidoVestuario = new javax.swing.JTextField();
        listaUsuariosDentroVestuario = new javax.swing.JTextField();
        colaEntradaVestuario = new javax.swing.JLabel();
        monitorVestuario = new javax.swing.JLabel();
        vestuariosVestuarios = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        PiscinaNiños = new javax.swing.JLabel();
        colaEntradaPiscinaNiños = new javax.swing.JLabel();
        monitorPiscinaNiños = new javax.swing.JLabel();
        niñosDentroPiscinaNiños = new javax.swing.JLabel();
        adultosDentroPiscinaNiños = new javax.swing.JLabel();
        listaColaEntradaPiscinaNiños = new javax.swing.JTextField();
        usuarioAtendidoPiscinaNiños = new javax.swing.JTextField();
        listaNiñosDentroPiscinaNiños = new javax.swing.JTextField();
        listaAdultosDentroPiscinaNiños = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        PiscinaOlas = new javax.swing.JLabel();
        colaEntradaPiscinaOlas = new javax.swing.JLabel();
        monitorPiscinaOlas = new javax.swing.JLabel();
        usuariosDentroPiscinaOlas = new javax.swing.JLabel();
        listaColaEntradaPiscinaOlas = new javax.swing.JTextField();
        usuarioAtendidoPiscinaOlas = new javax.swing.JTextField();
        listaUsuariosDentroPiscinaOlas = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        PiscinaGrande = new javax.swing.JLabel();
        colaEntradaPiscinaGrande = new javax.swing.JLabel();
        monitorPiscinaGrande = new javax.swing.JLabel();
        usuariosDentroPiscinaGrande = new javax.swing.JLabel();
        listaColaEntradaPiscinaGrande = new javax.swing.JTextField();
        listaUsuariosDentroPiscinaGrande = new javax.swing.JTextField();
        usuarioAtendidoPiscinaGrande = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        Tumbonas = new javax.swing.JLabel();
        colaEntradaTumbonas = new javax.swing.JLabel();
        monitorTumbonas = new javax.swing.JLabel();
        usuariosDentroTumbonas = new javax.swing.JLabel();
        listaColaEntradaTumbonas = new javax.swing.JTextField();
        usuarioAtendidoTumbonas = new javax.swing.JTextField();
        listaUsuariosDentroTumbonas = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        Toboganes = new javax.swing.JLabel();
        listaColaEntradaToboganes = new javax.swing.JTextField();
        colaEntradaToboganes = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        monitorA = new javax.swing.JLabel();
        toboganA = new javax.swing.JLabel();
        usuarioAtendidoToboganA = new javax.swing.JTextField();
        usuarioToboganA = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        B = new javax.swing.JLabel();
        monitorB = new javax.swing.JLabel();
        toboganB = new javax.swing.JLabel();
        usuarioAtendidoToboganB = new javax.swing.JTextField();
        usuarioToboganB = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        C = new javax.swing.JLabel();
        monitorC = new javax.swing.JLabel();
        toboganC = new javax.swing.JLabel();
        usuarioAtendidoToboganC = new javax.swing.JTextField();
        usuarioToboganC = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        botonReanudar = new javax.swing.JButton();
        botonPausa = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                                                                                                                            ***PARQUE ACUÁTICO - PEC3L***");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        ParqueAcuatico.setBackground(new java.awt.Color(0, 102, 204));
        ParqueAcuatico.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 16)); // NOI18N
        ParqueAcuatico.setForeground(new java.awt.Color(255, 255, 255));
        ParqueAcuatico.setText("                   PARQUE  ACUÁTICO");
        ParqueAcuatico.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        listaColaEntradaParqueAcuatico.setEditable(false);
        listaColaEntradaParqueAcuatico.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        colaEntradaParqueAcuatico.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaParqueAcuatico.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaParqueAcuatico.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaParqueAcuatico.setText("       COLA  ENTRADA:");
        colaEntradaParqueAcuatico.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(colaEntradaParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listaColaEntradaParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(listaColaEntradaParqueAcuatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(colaEntradaParqueAcuatico, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        Vestuario.setBackground(new java.awt.Color(0, 153, 153));
        Vestuario.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        Vestuario.setForeground(new java.awt.Color(255, 255, 255));
        Vestuario.setText("         VESTUARIOS");
        Vestuario.setOpaque(true);

        listaColaEntradaVestuario.setEditable(false);
        listaColaEntradaVestuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        listaColaEntradaVestuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        usuarioAtendidoVestuario.setEditable(false);
        usuarioAtendidoVestuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaUsuariosDentroVestuario.setEditable(false);
        listaUsuariosDentroVestuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        colaEntradaVestuario.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaVestuario.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaVestuario.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaVestuario.setText("       COLA  ENTRADA:");
        colaEntradaVestuario.setOpaque(true);

        monitorVestuario.setBackground(new java.awt.Color(0, 153, 204));
        monitorVestuario.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorVestuario.setForeground(new java.awt.Color(255, 255, 255));
        monitorVestuario.setText("             MONITOR:");
        monitorVestuario.setOpaque(true);

        vestuariosVestuarios.setBackground(new java.awt.Color(0, 153, 204));
        vestuariosVestuarios.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        vestuariosVestuarios.setForeground(new java.awt.Color(255, 255, 255));
        vestuariosVestuarios.setText("          VESTUARIOS:");
        vestuariosVestuarios.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monitorVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vestuariosVestuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaUsuariosDentroVestuario, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
                    .addComponent(listaColaEntradaVestuario)
                    .addComponent(usuarioAtendidoVestuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(741, Short.MAX_VALUE)
                .addComponent(Vestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(706, 706, 706))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Vestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaColaEntradaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monitorVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtendidoVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaUsuariosDentroVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vestuariosVestuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        PiscinaNiños.setBackground(new java.awt.Color(0, 153, 153));
        PiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        PiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaNiños.setText("   PISCINA DE NIÑOS");
        PiscinaNiños.setOpaque(true);

        colaEntradaPiscinaNiños.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaPiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaPiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaPiscinaNiños.setText("       COLA  ENTRADA:");
        colaEntradaPiscinaNiños.setOpaque(true);

        monitorPiscinaNiños.setBackground(new java.awt.Color(0, 153, 204));
        monitorPiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorPiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        monitorPiscinaNiños.setText("             MONITOR:");
        monitorPiscinaNiños.setOpaque(true);

        niñosDentroPiscinaNiños.setBackground(new java.awt.Color(0, 153, 204));
        niñosDentroPiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        niñosDentroPiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        niñosDentroPiscinaNiños.setText("                NIÑOS:");
        niñosDentroPiscinaNiños.setOpaque(true);

        adultosDentroPiscinaNiños.setBackground(new java.awt.Color(0, 153, 204));
        adultosDentroPiscinaNiños.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        adultosDentroPiscinaNiños.setForeground(new java.awt.Color(255, 255, 255));
        adultosDentroPiscinaNiños.setText("             ADULTOS:");
        adultosDentroPiscinaNiños.setOpaque(true);

        listaColaEntradaPiscinaNiños.setEditable(false);
        listaColaEntradaPiscinaNiños.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioAtendidoPiscinaNiños.setEditable(false);
        usuarioAtendidoPiscinaNiños.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaNiñosDentroPiscinaNiños.setEditable(false);
        listaNiñosDentroPiscinaNiños.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaAdultosDentroPiscinaNiños.setEditable(false);
        listaAdultosDentroPiscinaNiños.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(PiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(colaEntradaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listaColaEntradaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monitorPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(niñosDentroPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adultosDentroPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioAtendidoPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(listaAdultosDentroPiscinaNiños, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listaNiñosDentroPiscinaNiños, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colaEntradaPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaColaEntradaPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioAtendidoPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monitorPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaNiñosDentroPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niñosDentroPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaAdultosDentroPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adultosDentroPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        PiscinaOlas.setBackground(new java.awt.Color(0, 153, 153));
        PiscinaOlas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        PiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaOlas.setText("   PISCINA DE OLAS");
        PiscinaOlas.setOpaque(true);

        colaEntradaPiscinaOlas.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaPiscinaOlas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaPiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaPiscinaOlas.setText("       COLA  ENTRADA:");
        colaEntradaPiscinaOlas.setOpaque(true);

        monitorPiscinaOlas.setBackground(new java.awt.Color(0, 153, 204));
        monitorPiscinaOlas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorPiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        monitorPiscinaOlas.setText("             MONITOR:");
        monitorPiscinaOlas.setOpaque(true);

        usuariosDentroPiscinaOlas.setBackground(new java.awt.Color(0, 153, 204));
        usuariosDentroPiscinaOlas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        usuariosDentroPiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        usuariosDentroPiscinaOlas.setText("              DENTRO:");
        usuariosDentroPiscinaOlas.setOpaque(true);

        listaColaEntradaPiscinaOlas.setEditable(false);
        listaColaEntradaPiscinaOlas.setBackground(new java.awt.Color(255, 255, 255));
        listaColaEntradaPiscinaOlas.setForeground(new java.awt.Color(255, 255, 255));
        listaColaEntradaPiscinaOlas.setCaretColor(new java.awt.Color(255, 255, 255));
        listaColaEntradaPiscinaOlas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        listaColaEntradaPiscinaOlas.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        usuarioAtendidoPiscinaOlas.setEditable(false);
        usuarioAtendidoPiscinaOlas.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaUsuariosDentroPiscinaOlas.setEditable(false);
        listaUsuariosDentroPiscinaOlas.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(usuariosDentroPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monitorPiscinaOlas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colaEntradaPiscinaOlas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaUsuariosDentroPiscinaOlas, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(usuarioAtendidoPiscinaOlas)
                    .addComponent(listaColaEntradaPiscinaOlas))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(PiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaColaEntradaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monitorPiscinaOlas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtendidoPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaUsuariosDentroPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuariosDentroPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        PiscinaGrande.setBackground(new java.awt.Color(0, 153, 153));
        PiscinaGrande.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        PiscinaGrande.setForeground(new java.awt.Color(255, 255, 255));
        PiscinaGrande.setText("      PISCINA GRANDE");
        PiscinaGrande.setOpaque(true);

        colaEntradaPiscinaGrande.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaPiscinaGrande.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaPiscinaGrande.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaPiscinaGrande.setText("       COLA  ENTRADA:");
        colaEntradaPiscinaGrande.setOpaque(true);

        monitorPiscinaGrande.setBackground(new java.awt.Color(0, 153, 204));
        monitorPiscinaGrande.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorPiscinaGrande.setForeground(new java.awt.Color(255, 255, 255));
        monitorPiscinaGrande.setText("             MONITOR:");
        monitorPiscinaGrande.setOpaque(true);

        usuariosDentroPiscinaGrande.setBackground(new java.awt.Color(0, 153, 204));
        usuariosDentroPiscinaGrande.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        usuariosDentroPiscinaGrande.setForeground(new java.awt.Color(255, 255, 255));
        usuariosDentroPiscinaGrande.setText("              DENTRO:");
        usuariosDentroPiscinaGrande.setOpaque(true);

        listaColaEntradaPiscinaGrande.setEditable(false);
        listaColaEntradaPiscinaGrande.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaUsuariosDentroPiscinaGrande.setEditable(false);
        listaUsuariosDentroPiscinaGrande.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioAtendidoPiscinaGrande.setEditable(false);
        usuarioAtendidoPiscinaGrande.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monitorPiscinaGrande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaPiscinaGrande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuariosDentroPiscinaGrande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(listaUsuariosDentroPiscinaGrande, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaColaEntradaPiscinaGrande, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioAtendidoPiscinaGrande, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(PiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaColaEntradaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioAtendidoPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monitorPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariosDentroPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaUsuariosDentroPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        Tumbonas.setBackground(new java.awt.Color(0, 153, 153));
        Tumbonas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        Tumbonas.setForeground(new java.awt.Color(255, 255, 255));
        Tumbonas.setText("            TUMBONAS");
        Tumbonas.setOpaque(true);

        colaEntradaTumbonas.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaTumbonas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaTumbonas.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaTumbonas.setText("     COLA  ENTRADA:");
        colaEntradaTumbonas.setOpaque(true);

        monitorTumbonas.setBackground(new java.awt.Color(0, 153, 204));
        monitorTumbonas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorTumbonas.setForeground(new java.awt.Color(255, 255, 255));
        monitorTumbonas.setText("           MONITOR:");
        monitorTumbonas.setOpaque(true);

        usuariosDentroTumbonas.setBackground(new java.awt.Color(0, 153, 204));
        usuariosDentroTumbonas.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        usuariosDentroTumbonas.setForeground(new java.awt.Color(255, 255, 255));
        usuariosDentroTumbonas.setText("              DENTRO:");
        usuariosDentroTumbonas.setOpaque(true);

        listaColaEntradaTumbonas.setEditable(false);
        listaColaEntradaTumbonas.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioAtendidoTumbonas.setEditable(false);
        usuarioAtendidoTumbonas.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        listaUsuariosDentroTumbonas.setEditable(false);
        listaUsuariosDentroTumbonas.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(Tumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(colaEntradaTumbonas, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(monitorTumbonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuariosDentroTumbonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaColaEntradaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listaUsuariosDentroTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioAtendidoTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Tumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaColaEntradaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colaEntradaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioAtendidoTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monitorTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaUsuariosDentroTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariosDentroTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        Toboganes.setBackground(new java.awt.Color(0, 153, 153));
        Toboganes.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 13)); // NOI18N
        Toboganes.setForeground(new java.awt.Color(255, 255, 255));
        Toboganes.setText("        TOBOGANES");
        Toboganes.setOpaque(true);

        listaColaEntradaToboganes.setEditable(false);
        listaColaEntradaToboganes.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        colaEntradaToboganes.setBackground(new java.awt.Color(0, 153, 204));
        colaEntradaToboganes.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        colaEntradaToboganes.setForeground(new java.awt.Color(255, 255, 255));
        colaEntradaToboganes.setText("       COLA  ENTRADA:");
        colaEntradaToboganes.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        A.setBackground(new java.awt.Color(153, 153, 255));
        A.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("  A");
        A.setOpaque(true);

        monitorA.setBackground(new java.awt.Color(0, 153, 204));
        monitorA.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorA.setForeground(new java.awt.Color(255, 255, 255));
        monitorA.setText("  MONITOR:");
        monitorA.setOpaque(true);

        toboganA.setBackground(new java.awt.Color(0, 153, 204));
        toboganA.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        toboganA.setForeground(new java.awt.Color(255, 255, 255));
        toboganA.setText("  TOBOGÁN:");
        toboganA.setOpaque(true);

        usuarioAtendidoToboganA.setEditable(false);
        usuarioAtendidoToboganA.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioToboganA.setEditable(false);
        usuarioToboganA.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(toboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioToboganA))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(monitorA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(18, 30, Short.MAX_VALUE)
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(usuarioAtendidoToboganA)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monitorA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtendidoToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(153, 255, 255));

        B.setBackground(new java.awt.Color(153, 153, 255));
        B.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("  B");
        B.setOpaque(true);

        monitorB.setBackground(new java.awt.Color(0, 153, 204));
        monitorB.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorB.setForeground(new java.awt.Color(255, 255, 255));
        monitorB.setText("  MONITOR:");
        monitorB.setOpaque(true);

        toboganB.setBackground(new java.awt.Color(0, 153, 204));
        toboganB.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        toboganB.setForeground(new java.awt.Color(255, 255, 255));
        toboganB.setText("  TOBOGÁN:");
        toboganB.setOpaque(true);

        usuarioAtendidoToboganB.setEditable(false);
        usuarioAtendidoToboganB.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioToboganB.setEditable(false);
        usuarioToboganB.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(toboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioToboganB))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(monitorB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 112, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(usuarioAtendidoToboganB)))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monitorB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtendidoToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(153, 255, 255));

        C.setBackground(new java.awt.Color(153, 153, 255));
        C.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("  C");
        C.setOpaque(true);

        monitorC.setBackground(new java.awt.Color(0, 153, 204));
        monitorC.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        monitorC.setForeground(new java.awt.Color(255, 255, 255));
        monitorC.setText("  MONITOR:");
        monitorC.setOpaque(true);

        toboganC.setBackground(new java.awt.Color(0, 153, 204));
        toboganC.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 12)); // NOI18N
        toboganC.setForeground(new java.awt.Color(255, 255, 255));
        toboganC.setText("  TOBOGÁN:");
        toboganC.setOpaque(true);

        usuarioAtendidoToboganC.setEditable(false);
        usuarioAtendidoToboganC.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        usuarioToboganC.setEditable(false);
        usuarioToboganC.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(toboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioToboganC))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(monitorC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 119, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(usuarioAtendidoToboganC)))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monitorC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtendidoToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Toboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(706, 706, 706))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(colaEntradaToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listaColaEntradaToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Toboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaColaEntradaToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaEntradaToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));

        botonReanudar.setBackground(new java.awt.Color(0, 204, 204));
        botonReanudar.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonReanudar.setForeground(new java.awt.Color(255, 255, 255));
        botonReanudar.setText("REANUDAR");
        botonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReanudarActionPerformed(evt);
            }
        });

        botonPausa.setBackground(new java.awt.Color(0, 204, 204));
        botonPausa.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonPausa.setForeground(new java.awt.Color(255, 255, 255));
        botonPausa.setText("PAUSA");
        botonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausaActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(0, 204, 204));
        botonSalir.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(botonPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReanudar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(648, 648, 648))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParqueAcuatico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReanudarActionPerformed
        //Para reanudar el programa
        if (botonPulsado)
        {
            botonPulsado = false;
            paso.abrir();
        }
    }//GEN-LAST:event_botonReanudarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        //Cerrar el programa
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausaActionPerformed
        //Para pausar el programa
        if (!botonPulsado)
        {
            botonPulsado = true;
            paso.cerrar();
        }
    }//GEN-LAST:event_botonPausaActionPerformed

    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaParqueAcuatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaParqueAcuatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaParqueAcuatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaParqueAcuatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                try 
                {
                    new GraficaParqueAcuatico().setVisible(true);
                } 
                catch (InterruptedException ex) 
                {
                    Logger.getLogger(GraficaParqueAcuatico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel ParqueAcuatico;
    private javax.swing.JLabel PiscinaGrande;
    private javax.swing.JLabel PiscinaNiños;
    private javax.swing.JLabel PiscinaOlas;
    private javax.swing.JLabel Toboganes;
    private javax.swing.JLabel Tumbonas;
    private javax.swing.JLabel Vestuario;
    private javax.swing.JLabel adultosDentroPiscinaNiños;
    private javax.swing.JButton botonPausa;
    private javax.swing.JButton botonReanudar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel colaEntradaParqueAcuatico;
    private javax.swing.JLabel colaEntradaPiscinaGrande;
    private javax.swing.JLabel colaEntradaPiscinaNiños;
    private javax.swing.JLabel colaEntradaPiscinaOlas;
    private javax.swing.JLabel colaEntradaToboganes;
    private javax.swing.JLabel colaEntradaTumbonas;
    private javax.swing.JLabel colaEntradaVestuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField listaAdultosDentroPiscinaNiños;
    private javax.swing.JTextField listaColaEntradaParqueAcuatico;
    private javax.swing.JTextField listaColaEntradaPiscinaGrande;
    private javax.swing.JTextField listaColaEntradaPiscinaNiños;
    private javax.swing.JTextField listaColaEntradaPiscinaOlas;
    private javax.swing.JTextField listaColaEntradaToboganes;
    private javax.swing.JTextField listaColaEntradaTumbonas;
    private javax.swing.JTextField listaColaEntradaVestuario;
    private javax.swing.JTextField listaNiñosDentroPiscinaNiños;
    private javax.swing.JTextField listaUsuariosDentroPiscinaGrande;
    private javax.swing.JTextField listaUsuariosDentroPiscinaOlas;
    private javax.swing.JTextField listaUsuariosDentroTumbonas;
    private javax.swing.JTextField listaUsuariosDentroVestuario;
    private javax.swing.JLabel monitorA;
    private javax.swing.JLabel monitorB;
    private javax.swing.JLabel monitorC;
    private javax.swing.JLabel monitorPiscinaGrande;
    private javax.swing.JLabel monitorPiscinaNiños;
    private javax.swing.JLabel monitorPiscinaOlas;
    private javax.swing.JLabel monitorTumbonas;
    private javax.swing.JLabel monitorVestuario;
    private javax.swing.JLabel niñosDentroPiscinaNiños;
    private javax.swing.JLabel toboganA;
    private javax.swing.JLabel toboganB;
    private javax.swing.JLabel toboganC;
    private javax.swing.JTextField usuarioAtendidoPiscinaGrande;
    private javax.swing.JTextField usuarioAtendidoPiscinaNiños;
    private javax.swing.JTextField usuarioAtendidoPiscinaOlas;
    private javax.swing.JTextField usuarioAtendidoToboganA;
    private javax.swing.JTextField usuarioAtendidoToboganB;
    private javax.swing.JTextField usuarioAtendidoToboganC;
    private javax.swing.JTextField usuarioAtendidoTumbonas;
    private javax.swing.JTextField usuarioAtendidoVestuario;
    private javax.swing.JTextField usuarioToboganA;
    private javax.swing.JTextField usuarioToboganB;
    private javax.swing.JTextField usuarioToboganC;
    private javax.swing.JLabel usuariosDentroPiscinaGrande;
    private javax.swing.JLabel usuariosDentroPiscinaOlas;
    private javax.swing.JLabel usuariosDentroTumbonas;
    private javax.swing.JLabel vestuariosVestuarios;
    // End of variables declaration//GEN-END:variables
}
